# Generated by Django 3.2 on 2021-04-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Node_blap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nodeuser', models.CharField(max_length=50, verbose_name='nodeuser')),
                ('nodenum', models.IntegerField(verbose_name='nodenum')),
                ('BLAP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blap')),
            ],
        ),
    ]
